### ISSUE TITLE
Discuss in the team the repository interface

### ISSUE THREAD

**Issue by octogradiste** [echo-swent/echo#234]

**Comment by octogradiste** [comment]
I see two options: the first option is to keep it as is, meaning only `getUserProfile` can return `null` (as it might be that we have a user without a user profile) and all other getters do not return null. This is for sure the easier option, as we don't have to change anything... We simply make the assumption that we won't call a getter with an invalid id (when could this actually happen?). The second option would be to make all getters return null in case the object doesn't exist. Definitely the cleaner option, but we would have to adapt the UI to display some kind of error message/page. 

I don't think, in our case, it's worth the effort. In some real world app, it would make sense to treat all possible error cases gracefully, but as we have many other things to work on, we should focus on the things which will add the most value.

What's your opinion on this?

**Comment by unglazedstamp** [comment]
I can imagine one scenario where it can be useful to return `null`: A user X creates an event, then a user Y loads it on his map, then X deletes the event, then Y join the event after a while. In that case the join button will try to modify a non existing event, but I imagine that before modifying the event (join it), Y will have to get the event to modify the most recent version of the event (otherwise two people cannot join the same event without restarting the app). If the getter returns null, Y don't even try to modify the event, otherwise Y will try to modify a non existing event and it will be the responsability of the repository to handle the error.

It may really be challenging to catch all these specific cases where the UI will get a null event and stop his action. It's probably easier to catch exception in the repository and pretend the action has been done.
I agree with you that it's not worth the effort because the user has little chance to experience one of these cases.

**Comment by violoncelloCH** [comment]
> We simply make the assumption that we won't call a getter with an invalid id (when could this actually happen?).

I don't think we can make this assumption. In addition to the case mentioned by @unglazedstamp: If we are unable to fetch from supabase and the event in the meantime expired from local cache we won't have anything to return.

> In that case the join button will try to modify a non existing event, but I imagine that before modifying the event (join it), Y will have to get the event to modify the most recent version of the event (otherwise two people cannot join the same event without restarting the app).

Well technically joining the event is not modifying the event itself but creating an entry in the relations table. This however will fail since the referenced element doesn't exist anymore.

While I agree on the point of not over-doing things here for now, I think we still need to figure out what to do in the case of accessing an inexistant object. If we catch the error in the repository or the data source, we still need to return something. If it's not a nullable attribute, we need to return some data. I don't know what we'd put there so that it makes sense. That's why I'm questioning if it really makes sense to go for this approach.

**Comment by octogradiste** [comment]
> I don't know what we'd put there so that it makes sense.

Maybe we could return an `EMPTY` object for now. Would avoid changing the UI and solve your problem of not knowing what to return.

**Comment by octogradiste** [comment]
> If we are unable to fetch from supabase and the event in the meantime expired from local cache we won't have anything to return.

In this case, we are in offline mod and we simply return everything we have (including expired data). It will be visible in the UI that we are in offline mode. So, the user will know that the data might be not up-to-date (how could it be if he is offline).

**Comment by octogradiste** [comment]
Maybe before the Tuesday meeting, we should clearly list the types of cases for which it makes sense to return null and how often this case could occur and what other options we have to prevent this (e.g. throw an error, avoid this case through the UI, etc.).

**Comment by octogradiste** [comment]
One case which would lead to an invalid `eventId` is the following:

The user is offline, all events are shown on the map. The user is back online and clicks on an event which was deleted while he was offline. As the event has expired, it's fetched from the remote data source, which will throw an error...
