### ISSUE TITLE
Discuss how to use the local data source not only for the offline mode, but also for caching.

### ISSUE THREAD

**Issue by octogradiste** [echo-swent/echo#235]

**Comment by octogradiste** [comment]
Firstly, if the app is in offline mode, the repository should only support getting objects, not setting (setting should not do anything). This is something we will need to adapt in the UI. The edit/create/join buttons should be grayed out and not be clickable... I think this is the way to go, as it avoid syncing once the app is online.

Then for caching, I see it as follows:

1. Fetch from the local data source (with some appropriate `syncedSecondsAgo`)
2. If the object is not null, return it (avoids a call to the network)
3. If the object is null, get it from the remote data source and cache it locally

If the user updates/creates an object, it's a bit more tricky. I'd suggest the following: set the object on the remote data source, and if the operation is successful set it locally. This doesn't offer the best performance, as we could set the object on the remote and local data source at the same time. But we would have to handle the case where setting the object on the remote data source fails (somehow delete the object locally, might lead to strange bugs). 

What's your opinion on this?

**Comment by unglazedstamp** [comment]
#### offline mode
I agree with you, but what happens if a user tries to get data that the cache doesn't have (e.g. subscribed events) while in offline mode ? should the app pretend it doesn't exist or display a kind of loading sign ? Personally I prefer to not display the data and add an offline mention on every screen to clearly show that it's offline mode.

#### caching
I would not try to optimize the performances for the setters because it's not a lot of data that are in transit to set an object and it's better to have a simple algorithm for now and improve it if we see that the app is not usable. For what I have seen for now, saving an event isn't long (< 5s) and the major speed improvement will be to get the lists of objects (events, tags, associations,...) which can be long enough to be noticeable by the user. An improvement could be to get some data, like the list of tags, at the start of the app to avoid some visible latency for the user.

**Comment by violoncelloCH** [comment]
I agree on pretty much all that has been said here!
Only thing I'd do differently on the UI: If already online, it should not even be possible to access the create/update event screens (with a visible hint). If the device disconnects while the user is on the creation page, graying out the save button is acceptable, but otherwise it might be frustrating if you enter all the details about your event to then realize that you can't save it.

**Comment by octogradiste** [comment]
I've been implementing the `LocalDataSource` and thought about the case where a `getAll` function is called on the `Repository`. In this case, what we should probably do is:

1. Call `getAllSyncedBefore` on the `LocalDataSource`
2. If the returned list of ids is not null, fetch them from the `RemoteDataSource` and save them locally.
3. Call `getAll` on the `LocalDataSource` and return it.
